imports:
    - { resource: project_defaults.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:          { asset_reset: %asset_reset%, top_cms_links: %top_cms_links% }

# SSI config
crunch_ssi:
    inline:     false
    use_header: true

# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ ]
#    java: "%java_path%"
#    filters:
#        cssrewrite: ~
#        sass: ~
#        compass: ~
#        closure:
#            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#    assets:
#        demo_css:
#            inputs:
#                - "@ONGRDemoBundle/Resources/public/style/ongr.scss"
#            filters:
#                - compass
#        demo_js:
#            inputs:
#                - "@ONGRDemoBundle/Resources/public/scripts/**/*.js"
#                - "@ONGRDemoBundle/Resources/public/scripts/main.js"
#            filters:
#                - closure


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

ongr_content:
    es:
        repositories:
            product: es.manager.default.lot
            content: es.manager.default.lot
            category: es.manager.default.lot

#ongr_router:
#    es_manager: default
#    seo_routes:
#        lot:
#            _route: ongr_lot
#            _controller: KTUBundle:Lot:document
#            _default_route: ongr_lot
#            _id_param: document


ongr_elasticsearch:
    connections:
        default:
            hosts:
                - { host: 127.0.0.1:9200 }
            index_name: zuv
            settings:
                number_of_shards: 2
                number_of_replicas: 0
                index:
                    refresh_interval: -1
    managers:
        default:
            connection: default
            mappings:
                - KTUForestBundle

ongr_filter_manager:
    managers:
        default:
            filters:
                - pager
                - sorting
            repository: 'lot'
    filters:
        pager:
            pager:
                request_field: 'page'
                count_per_page: 9
        sort:
            sorting:
                request_field: 'sort'
                choices:
                    - { label: Price ascending, field: price, default: true }
                    - { label: Price descending, field: price, order: desc }
                    - { label: Title ascending, field: title }
                    - { label: Title descending, field: title, order: desc }
