#Content controller
zuv_demo_homepage:
    path:     /
    defaults: { _controller: KTUForestBundle:Content:homePage }
zuv_demo_provinces:
    path:     /provinces
    defaults: { _controller: KTUForestBundle:Content:provinces }
zuv_tree_type:
    path:     /treeInfo/{treeType}
    defaults: { _controller: KTUForestBundle:Content:treeInfo, treeType: 'Eglė'}
