parameters:
    provinces_map: src/KTU/ForestBundle/Resources/config/provinces.yml

services:
    forest.data.import:
        class: KTU\ForestBundle\Service\ImportService
        arguments: [@es.manager]
        calls:
            - [setProvinceMapFile, [%provinces_map%]]

    forest.data.collector:
        class: KTU\ForestBundle\Service\DataCollectorService
        arguments: [@es.manager]

    tree.info.collector:
        class: KTU\ForestBundle\Service\TreeInfoCollector
        arguments: [@es.manager]
